version: '3.4'

services:
  db:
    image: marcelv/windowsservercore/sqlserver:1809
    expose:
     - "1433"
    ports:
     - "1433:1433"
    environment:
      ACCEPT_EULA: 'Y'
      sa_password: 'mypassword123!@'
 
  aspnetdb:
    image: marcelv/aspnetdb
    expose:
     - "1433"
    ports:
     - "1434:1433"
    environment:
      sa_password: 'mypassword123!@'

networks:
  default:
    external:
      name: nat